# Generated by Django 4.2.14 on 2024-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=10),
            preserve_default=False,
        ),
    ]
