# Generated by Django 4.2.14 on 2024-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetable'), ('FRUIT', 'Fruit')], default='FRUIT', max_length=5),
        ),
    ]
