# Generated by Django 4.2.14 on 2024-08-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Organic_Product',
        ),
    ]
