# Generated by Django 4.2.14 on 2024-08-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_product_organic_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.organic_product',),
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
            ],
            options={
                'verbose_name': 'Vegetable',
                'verbose_name_plural': 'Vegetables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.organic_product',),
        ),
    ]
