# Generated by Django 4.2.14 on 2024-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('facts_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('information', models.TextField()),
            ],
        ),
    ]
