# Generated by Django 4.2.14 on 2024-08-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
