# Generated by Django 4.2.14 on 2024-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_billingdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
    ]
