# Generated by Django 4.2.14 on 2024-08-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_billingdetail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
