# Generated by Django 4.2.14 on 2024-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cartitem_discount_cartitem_subtotal_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='organic_product',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organic_product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
