# Generated by Django 4.2.14 on 2024-08-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_organic_product_country_organic_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organic_product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
