# Generated by Django 4.2.14 on 2024-08-16 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_organic_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
