# Generated by Django 4.2.14 on 2024-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_billingdetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
