# Generated by Django 4.2.14 on 2024-08-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_billingdetail_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetail',
            name='discount',
        ),
    ]
