# Generated by Django 4.2.14 on 2024-08-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_banner_created_at_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organic_Product',
            new_name='Products',
        ),
    ]
